import { newId } from '@businessos/shared';
import { sql } from 'drizzle-orm';
import { pgPolicy, timestamp, uuid } from 'drizzle-orm/pg-core';

/** UUIDv7 primary key generated by the application. */
export const primaryId = () =>
  uuid()
    .primaryKey()
    .$defaultFn(() => newId());

export const createdAt = () => timestamp({ withTimezone: true }).notNull().defaultNow();

export const updatedAt = () =>
  timestamp({ withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

export const timestamps = () => ({
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

/**
 * Standard row-level security for tenant-owned tables (ADR-005): rows are visible and writable
 * only inside `withTenant` for the same organization, or inside `withSystem`.
 */
export function tenantIsolationPolicy() {
  return pgPolicy('tenant_isolation', {
    as: 'permissive',
    for: 'all',
    using: sql`app_is_system() OR organization_id = app_current_org()`,
    withCheck: sql`app_is_system() OR organization_id = app_current_org()`,
  });
}
