import { ProviderError } from '@businessos/shared';
import { createHash, createHmac } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * Object storage port. Keys are generated by the platform (`<organizationId>/<fileId>`), never
 * taken from users. Provider-specific code (paths, signing) stays inside adapters.
 */
export interface FileStorage {
  readonly name: string;
  status(): 'ready' | 'configuration_required';
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer>;
  /** Removes an object; succeeds when it is already gone. */
  delete(key: string): Promise<void>;
}

export const STORAGE_KEY = /^[0-9a-f-]{36}\/[0-9a-f-]{36}$/;

function assertKey(key: string): void {
  if (!STORAGE_KEY.test(key)) throw new Error('invalid storage key');
}

/** In-process storage for tests. */
export class MemoryFileStorage implements FileStorage {
  readonly name = 'memory';
  readonly objects = new Map<string, { body: Buffer; contentType: string }>();
  failNextPut = false;

  status() {
    return 'ready' as const;
  }

  put(key: string, body: Buffer, contentType: string): Promise<void> {
    assertKey(key);
    if (this.failNextPut) {
      this.failNextPut = false;
      return Promise.reject(new ProviderError('memory', 'Storage is unavailable'));
    }
    this.objects.set(key, { body: Buffer.from(body), contentType });
    return Promise.resolve();
  }

  get(key: string): Promise<Buffer> {
    assertKey(key);
    const object = this.objects.get(key);
    if (!object) return Promise.reject(new ProviderError('memory', 'Object not found'));
    return Promise.resolve(object.body);
  }

  delete(key: string): Promise<void> {
    assertKey(key);
    this.objects.delete(key);
    return Promise.resolve();
  }
}

/** Local disk (development and single-node installs). */
export class LocalFileStorage implements FileStorage {
  readonly name = 'local';

  constructor(private readonly root: string) {}

  status() {
    return 'ready' as const;
  }

  private pathOf(key: string): string {
    assertKey(key);
    const resolved = path.resolve(this.root, key);
    if (!resolved.startsWith(`${path.resolve(this.root)}${path.sep}`)) {
      throw new Error('invalid storage key');
    }
    return resolved;
  }

  async put(key: string, body: Buffer, _contentType?: string): Promise<void> {
    const target = this.pathOf(key);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, body, { mode: 0o600 });
  }

  async get(key: string): Promise<Buffer> {
    try {
      return await readFile(this.pathOf(key));
    } catch (error) {
      throw new ProviderError('local', 'Stored file is missing', { cause: error });
    }
  }

  async delete(key: string): Promise<void> {
    await rm(this.pathOf(key), { force: true });
  }
}

// ── S3-compatible storage (AWS S3, Cloudflare R2, MinIO…) ────────────────────────────────

const sha256Hex = (value: string | Buffer) => createHash('sha256').update(value).digest('hex');
const hmac = (key: string | Buffer, value: string) =>
  createHmac('sha256', key).update(value).digest();

function encodeSegment(segment: string): string {
  return encodeURIComponent(segment).replace(
    /[!'()*]/g,
    (char) => `%${char.charCodeAt(0).toString(16).toUpperCase()}`,
  );
}

export interface SignInput {
  method: string;
  /** Absolute URL of the request. */
  url: URL;
  /** Headers to sign (lower-case names); must include `host`. */
  headers: Record<string, string>;
  payloadHash: string;
  region: string;
  service?: string;
  accessKeyId: string;
  secretAccessKey: string;
  /** `YYYYMMDDTHHMMSSZ`. */
  amzDate: string;
}

/** AWS Signature Version 4 `Authorization` header. */
export function signV4(input: SignInput): string {
  const service = input.service ?? 's3';
  const date = input.amzDate.slice(0, 8);
  const canonicalUri = input.url.pathname
    .split('/')
    .map((segment) => encodeSegment(decodeURIComponent(segment)))
    .join('/');
  const canonicalQuery = [...input.url.searchParams.entries()]
    .map(([key, value]) => [encodeSegment(key), encodeSegment(value)] as const)
    .sort(([a, av], [b, bv]) => (a === b ? av.localeCompare(bv) : a < b ? -1 : 1))
    .map(([key, value]) => `${key}=${value}`)
    .join('&');
  const names = Object.keys(input.headers)
    .map((name) => name.toLowerCase())
    .sort();
  const lower = Object.fromEntries(
    Object.entries(input.headers).map(([name, value]) => [name.toLowerCase(), value]),
  );
  const canonicalHeaders = names
    .map((name) => `${name}:${(lower[name] ?? '').trim().replace(/\s+/g, ' ')}\n`)
    .join('');
  const signedHeaders = names.join(';');
  const canonicalRequest = [
    input.method,
    canonicalUri,
    canonicalQuery,
    canonicalHeaders,
    signedHeaders,
    input.payloadHash,
  ].join('\n');
  const scope = `${date}/${input.region}/${service}/aws4_request`;
  const stringToSign = ['AWS4-HMAC-SHA256', input.amzDate, scope, sha256Hex(canonicalRequest)].join(
    '\n',
  );
  const signingKey = hmac(
    hmac(hmac(hmac(`AWS4${input.secretAccessKey}`, date), input.region), service),
    'aws4_request',
  );
  const signature = createHmac('sha256', signingKey).update(stringToSign).digest('hex');
  return `AWS4-HMAC-SHA256 Credential=${input.accessKeyId}/${scope}, SignedHeaders=${signedHeaders}, Signature=${signature}`;
}

export interface S3Config {
  /** e.g. `https://s3.me-south-1.amazonaws.com` or an R2/MinIO endpoint. */
  endpoint: string;
  region: string;
  bucket: string;
  accessKeyId: string | null;
  secretAccessKey: string | null;
  fetch?: typeof fetch;
  now?: () => Date;
  timeoutMs?: number;
}

/**
 * S3-compatible adapter (path-style requests, SigV4). CONFIGURATION_REQUIRED without keys: it
 * reports `configuration_required` and refuses to call the provider.
 */
export class S3FileStorage implements FileStorage {
  readonly name = 's3';
  private readonly fetchImpl: typeof fetch;

  constructor(private readonly config: S3Config) {
    this.fetchImpl = config.fetch ?? fetch;
  }

  status() {
    return this.config.accessKeyId && this.config.secretAccessKey
      ? ('ready' as const)
      : ('configuration_required' as const);
  }

  private async request(
    method: 'PUT' | 'GET' | 'DELETE',
    key: string,
    body?: Buffer,
    contentType?: string,
  ) {
    assertKey(key);
    const { accessKeyId, secretAccessKey } = this.config;
    if (!accessKeyId || !secretAccessKey) {
      throw new ProviderError('s3', 'File storage is not configured (CONFIGURATION_REQUIRED)');
    }
    const url = new URL(
      `${this.config.endpoint.replace(/\/+$/, '')}/${encodeSegment(this.config.bucket)}/${key}`,
    );
    const amzDate = (this.config.now?.() ?? new Date())
      .toISOString()
      .replace(/[-:]/g, '')
      .replace(/\.\d{3}/, '');
    const payloadHash = sha256Hex(body ?? '');
    const headers: Record<string, string> = {
      host: url.host,
      'x-amz-content-sha256': payloadHash,
      'x-amz-date': amzDate,
      ...(contentType ? { 'content-type': contentType } : {}),
    };
    const authorization = signV4({
      method,
      url,
      headers,
      payloadHash,
      region: this.config.region,
      accessKeyId,
      secretAccessKey,
      amzDate,
    });
    let response: Response;
    try {
      response = await this.fetchImpl(url, {
        method,
        headers: { ...headers, authorization },
        ...(body ? { body } : {}),
        signal: AbortSignal.timeout(this.config.timeoutMs ?? 30_000),
      });
    } catch (error) {
      throw new ProviderError('s3', 'Could not reach file storage', {
        retryable: true,
        cause: error,
      });
    }
    return response;
  }

  async put(key: string, body: Buffer, contentType: string): Promise<void> {
    const response = await this.request('PUT', key, body, contentType);
    if (!response.ok) {
      throw new ProviderError('s3', `File storage rejected the upload (${response.status})`, {
        retryable: response.status >= 500,
      });
    }
  }

  async get(key: string): Promise<Buffer> {
    const response = await this.request('GET', key);
    if (!response.ok) {
      throw new ProviderError('s3', `File storage read failed (${response.status})`, {
        retryable: response.status >= 500,
      });
    }
    return Buffer.from(await response.arrayBuffer());
  }

  async delete(key: string): Promise<void> {
    const response = await this.request('DELETE', key);
    if (!response.ok && response.status !== 404) {
      throw new ProviderError('s3', `File storage delete failed (${response.status})`, {
        retryable: response.status >= 500,
      });
    }
  }
}

export interface StorageConfig {
  driver: 'local' | 's3';
  localDir: string;
  s3: {
    endpoint?: string | undefined;
    region?: string | undefined;
    bucket?: string | undefined;
    accessKeyId?: string | undefined;
    secretAccessKey?: string | undefined;
  };
}

/** The configured storage (shared by the API and the worker). */
export function createFileStorage(config: StorageConfig): FileStorage {
  if (config.driver === 'local') return new LocalFileStorage(path.resolve(config.localDir));
  return new S3FileStorage({
    endpoint: config.s3.endpoint ?? `https://s3.${config.s3.region ?? 'me-south-1'}.amazonaws.com`,
    region: config.s3.region ?? 'me-south-1',
    bucket: config.s3.bucket ?? 'businessos-files',
    accessKeyId: config.s3.accessKeyId ?? null,
    secretAccessKey: config.s3.secretAccessKey ?? null,
  });
}
